apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - licenses-web/deployment-manifest.yaml
  - products-service/deployment-manifest.yaml
  - api-gateway/deployment-manifest.yaml