apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-deployment
  labels:
    app: products-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: lopesdev/product-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
