apiVersion: apps/v1
kind: Deployment
metadata:
  name: licenses-web-deployment
  labels:
    app: licenses-web
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: licenses-web
  template:
    metadata:
      labels:
        app: licenses-web
    spec:
      containers:
        - name: licenses-web
          image: lopesdev/licenses-web:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://products-service:80"
            - name: NEXTAUTH_URL
              value: "https://linkify.systems"
            - name: NEXTAUTH_SECRET
              value: "kpyF9I93qEVOVhuM4NLxsf0rMfQ9Er+KthUPLuX84cY="
            - name: KEYCLOAK_CLIENT_ID
              value: "licenses-web-client"
            - name: KEYCLOAK_ISSUER
              value: "https://auth.linkify.systems/realms/magic-keys"
---
apiVersion: v1
kind: Service
metadata:
  name: licenses-web
spec:
  selector:
    app: licenses-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
