apiVersion: apps/v1
kind: Deployment
metadata:
  name: licenses-web-deployment
  labels:
    app: licenses-web
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: licenses-web
  template:
    metadata:
      labels:
        app: licenses-web
    spec:
      containers:
        - name: licenses-web
          image: lopesdev/licenses-web:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: licenses-web
spec:
  selector:
    app: licenses-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
